In [6]:
import pandas as pd

In [7]:
Dataset = pd.read_csv("Salary_Data.csv") #loading dataset

In [8]:
Dataset #printing dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [9]:
#Declaring input variable
Independent = Dataset[["YearsExperience"]]
Independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [10]:
#Declaring output variable
Dependent = Dataset[["Salary"]]
Dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [11]:
#Split train and test data from dataset
from sklearn.model_selection import train_test_split
#train_test_split(Independent, Dependent, test_size = 0.30, random_state = 0) 
# will generate 4 sets of split data, 2 for train(x,y) and 2 for test(x,y)
x_train, x_test, y_train, y_test = train_test_split(Independent, Dependent, test_size = 0.30, random_state = 0) 
#print(x_train, x_test, y_train, y_test)

    YearsExperience
22              7.9
5               2.9
16              5.1
8               3.2
14              4.5
23              8.2
20              6.8
1               1.3
29             10.5
6               3.0
4               2.2
18              5.9
19              6.0
9               3.7
7               3.2
25              9.0
3               2.0
0               1.1
21              7.1
15              4.9
12              4.0     YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
27              9.6
11              4.0
17              5.3       Salary
22  101302.0
5    56642.0
16   66029.0
8    64445.0
14   61111.0
23  113812.0
20   91738.0
1    46205.0
29  121872.0
6    60150.0
4    39891.0
18   81363.0
19   93940.0
9    57189.0
7    54445.0
25  105582.0
3    43525.0
0    39343.0
21   98273.0
15   67938.0
12   56957.0       Salary
2    37731.0
28  122391.0
13   57081.0
10   63218.0
26  116969.0
24  109431.0
27  112635.0
11   55794.0
17   83088.0

In [31]:
#SIMPLE LINEAR REGRESSION MODEL CREATION AND EVALUATION

#Pandas is a powerful, open-source Python library used for data manipulation and analysis. 
#It is a data preparation powerhouse. 
#You'll use it to load, clean, explore, and prepare your data before feeding it to sklearn for machine learning
import pandas as pd

#importing data set to 'Dataset' variable using pandas and read_csv function
Dataset = pd.read_csv("Salary_Data.csv") #loading dataset
Dataset

#declaring input and output variables from the dataset for analysis
Independent = Dataset[["YearsExperience"]]
Independent
Dependent = Dataset[["Salary"]]
Dependent

#Spliting train and test data from dataset to evaluate and analyse 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(Independent, Dependent, test_size = 0.30, random_state = 0) 

#bulding Simple linear regression model
#Sklearn -> Scikit-learn is a most popular machine learning library in Python
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()
# fit(x,y) -> It is an SKLearn API where it trains the model and is always used first
regressor. fit(x_train, y_train)

#calculating weight and bias
weight = regressor.coef_
bias = regressor.intercept_
print(f" Bias for the linear model from the data set is {bias}")
print(f" Weight for the linear model from the data set is {weight}")

#Y-prediction -> predicting the SRL from test data set 
y_predict = regressor.predict(x_test)

#Evaluation metrics using r2 using predicted value and test data's actual value
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_predict)
print(f" The r2 score for the linear regression model is {r_score}")
if r_score > 0 and r_score < 1 :
    print(f"The predicted Simple Linear Regression Model has better performance with {r_score} r2 score")
else:
    print(f"The predicted Simple Linear Regression Model is not having better performance with {r_score} r2 score")

#Save the model
import pickle
#It saves the trained machine learning models to your hard drive so you can use them later without retraining!

filename = "Final_model_SLR.sav" #declaring a pickle file name
pickle.dump(regressor,open (filename, 'wb'))#creating a pickle file in the local repo
loaded_model = pickle.load(open("Final_model_SLR.sav", 'rb')) #loading the pickle file 
result = loaded_model.predict([[12]])
print(f'The predicted salary that can be given for the given years of experiance is {result}')

 Bias for the linear model from the data set is [26777.3913412]
 Weight for the linear model from the data set is [[9360.26128619]]
 The r2 score for the linear regression model is 0.9740993407213511
The predicted Simple Linear Regression Model has better performance with 0.9740993407213511 r2 score
The predicted salary that can be given for the given years of experiance is [[139100.52677552]]

C:\Users\Dhivya\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(